name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH known hosts
          run: |
            ssh-keyscan -H 18.212.87.23 >> ~/.ssh/known_hosts

      
