name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: "18.212.87.23"
          username: "ubuntu"
          key: '-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAv32fELCdzFX79406FgP3ncIIgZof7znNm24rMogDl8do/u4w
YG5XtGCBSg+gvCT2iXc1umSj8zU0sKpPZi2vRJU0rS1d6s+Hg4XiaEEBB4gTLkHa
OcpfesFeDC360fsjxjS+ZTExKYawZ3gMssnur+FDxgpkCtJxIA10Wp9lyrFUR1fb
UW7vGjwpNdSgtp0/nyVWGWa/qqSr4T0uVcPr/AeYppl7BwnhEhcsCrd76kFcPMAL
Vo7nWxeJ/hbIiu5kGPcWewGFyfyJ3SybBN+w9Wjcp79or8e+VHYGOIBL0GV3TEE2
toPdi9ALmt3QdI7mIYoxwDXAVkBQHXB/JysYFwIDAQABAoIBAEDlD70WPcP799Ij
OGYxnf8GvN8/HkdybW2ZXmZXlfAgEkMi8Z4chviIJAi3Vx+r3ykjD0BFzxIjG+Ir
NZFJNjal4h42W7ex8RjvjJUMQo8M3IM2qgAfx0/QrFCwXGpBFBSd11Bv5VtPXAUU
uCj3Kj7Mtq0s5E6Oluvn42C62EJiU9IAB4vRCVSxzIp+86p1LByWnn6+a5dj/r0y
Isv3Mpzkl970gCUvrhAzvm75dl6RMUgjTwj7vVVX+6Lb32oPgdlqsFK5kDMCHpmz
CWpiFYhEArH1U1CK8igXcgGo93N5yTDQGytgX/eq4xp00Zqhq7KJfzqCCCpZj8u2
GeCn7AECgYEA7p7Nw3r4XdJuNwrb40pnrOEw7CXbzV57EGAh6MqF+aRdemCSY5ZI
Z2Eac16ghWf4QPXodZtWZZU0InITZMqj2+G6B1kUv7YQpSTjvCeZEpU9PRLubtG2
gdAweqVnMA95ZAS+WQyn6OcKC+sTXc69aPrvQqPeiUTFAY8pyTbfMRcCgYEAzXAP
5WZ3bia74aijPFWhi58aEcg9QU0cyeVIjBV9LGk9ZJzLMCIr03W4kgEtp4HOd9Fh
xa1zCLX9ZYgZlhNueOXs7lXXQUPGb/XLGvgpOjsVe1HfAB3CRd02puzmbQJavlir
pXGpelNdVKqa1+bEHVGD+ewffTCs0oSGr8ZdsQECgYA/iCaOumnwSPuxSgHblU7f
N6HX7giEuHgZlw7QNUPQgNOmppmzTCsA41iwiOxCOLlfSlnXHkG1kDEuTqMdPdq8
y2/FTxF4LZhm79h2mzBlQzjnzueOt+VY0L5nmSxNHoGagKzRds4p84G4RKGGY2oI
zm7vlkPE1nuBe8WLXkG0hwKBgFwQzm7l3rv0i9pzMsRFM+JYaNxzOlBbeH1aTYrJ
zpDqkOLYCY8GoVFgvlhgQs+AssCriv+F3bmXpXms5pqFFssDb4zX12GeN/3QzzbE
4+T+uX/Mjv2EWJ3qpyVjoVhU58nJ/xJjv6ncVkUtN7tt5ZGmCFkmYm4+NBUb4yg+
45oBAoGBAJt5OSMRB2S+4es9oDQyWqm2lmkuSelAWr53tMRAup1V4yJMZJ9uD7x3
U6V0ZkUZ5veIXFViNkc4V3PDx2wKHKJJVhWBRhqjmTtjNiVllhXag4OwDZtL6Ze8
uKfJIWAOR2A6KbqR8fIJv0Ife/YnlIeIVEecnjWZwTp4Ckb5H4Ah
-----END RSA PRIVATE KEY-----'
          script: whoami
