name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 18.212.87.23 >> ~/.ssh/known_hosts

      - name: Connect to EC2 and Run Commands
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@18.212.87.23 "echo 'Connected to EC2 successfully!'"
