name: SSH Connection Example

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: "18.212.87.23"
          username: "ubuntu"
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            echo "Connecting to server..."
            # Add the commands to execute on the server
            ls -l
