name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main  # Change to your deployment branch
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: "18.212.87.23" # Replace with your EC2 IP
          username: "ubuntu"    # Change if using a different user
          key: "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAtKjDbixn/8DRjhYBo/11tXxHeaf04EusruD8BSTLtz71uIefsRG1
f0CKYFKDw9Jl8rrjJQPfLnqe/ubPeFwctbuFmaYfoU9tgfU7Pa2WixAguKh6ZTwuhlydp6
7dBV/gJ5VMJHAzaWe7fnoP+J4pWYHl5MOtZd9Wj66+s8pTGQuYHbHZToRikpeKYtUNL41r
Q3qrCSi1aXLSFhLgZnr9XTUZZPmVU4ghMFv4YSR5bOwrrKWv8Tf9fsSTgNs6lqQoLDr4EB
SzfOZMgpfVPfcDnhAFTMvrZfkV35Wx9vbp4HXR4fFym3glXk/dXPz4QxlsuA6TwJTqzQaL
usup6Jis2eZ/Q/1cWeVxTeN+8VQ/tc6uI88rWGjI7GrQuez5DCzewf18bXmsdAcjY9+6dN
of5kowMYJPtMMCOlR7xQhS1SIhE5nzX76U4IOktkaOATBrZhWBlxpf6/LGCY8tGTKlxsiv
zzjOyeiboHQ9XD2jShhlZU71BBt6jLYDZl0ArnlfrDPBENsr7rGsGSdE3D3IrlqvrDZbv5
ef25hgu5mKLPcB1BGj03ARbUz52Ue/g4OxjIYiGccnV3zRvJmZQGK7hokgR9XwUtN5rHTH
t6vLhe5X9k+Ee6b/WOdzCYIBj0bRPWrah0KWxETz36drMvAGzOk5BwXTQbc8d6mOyArPC3
kAAAdQnvQ8Zp70PGYAAAAHc3NoLXJzYQAAAgEAtKjDbixn/8DRjhYBo/11tXxHeaf04Eus
ruD8BSTLtz71uIefsRG1f0CKYFKDw9Jl8rrjJQPfLnqe/ubPeFwctbuFmaYfoU9tgfU7Pa
2WixAguKh6ZTwuhlydp67dBV/gJ5VMJHAzaWe7fnoP+J4pWYHl5MOtZd9Wj66+s8pTGQuY
HbHZToRikpeKYtUNL41rQ3qrCSi1aXLSFhLgZnr9XTUZZPmVU4ghMFv4YSR5bOwrrKWv8T
f9fsSTgNs6lqQoLDr4EBSzfOZMgpfVPfcDnhAFTMvrZfkV35Wx9vbp4HXR4fFym3glXk/d
XPz4QxlsuA6TwJTqzQaLusup6Jis2eZ/Q/1cWeVxTeN+8VQ/tc6uI88rWGjI7GrQuez5DC
zewf18bXmsdAcjY9+6dNof5kowMYJPtMMCOlR7xQhS1SIhE5nzX76U4IOktkaOATBrZhWB
lxpf6/LGCY8tGTKlxsivzzjOyeiboHQ9XD2jShhlZU71BBt6jLYDZl0ArnlfrDPBENsr7r
GsGSdE3D3IrlqvrDZbv5ef25hgu5mKLPcB1BGj03ARbUz52Ue/g4OxjIYiGccnV3zRvJmZ
QGK7hokgR9XwUtN5rHTHt6vLhe5X9k+Ee6b/WOdzCYIBj0bRPWrah0KWxETz36drMvAGzO
k5BwXTQbc8d6mOyArPC3kAAAADAQABAAACAFi0YLkQ/sOaNoqwjX+q7Qf+jM3URS14msKH
X9dauNgyBs7jcOqtilOAKjGfcmlNPpePYgaDvysANF9uj0JG4CXvfGr0IaW/7UIZWkwvlr
KTaa2hs+9PPHzmrtZtysJf0B0/dlKR8Px5XZt9bagiaKU1Xd8UoWha4BLOt35qAqFSiw9R
iyS9ZfUaiW17tOy7YIaSjbaCkYjEQxlpjVtkWlFQyDZHQiXwunMXRX7VPPXZhJxSAnDLkC
GVfeOQQVVEJyGIltK2h2b1YW3iBWdWiSUsMp4BpoS8aBwPUYG0vSNkVni9aAukU5zaVBPb
dj7kFfjN14iA1kVzSFqgs72scXn603/lDiIhXzXwUagIy9DNh99NCM8ZiB1OxwOOpvvzXk
GvXEBr5O3msO8WYQRLKymWbYnvDKsLfKPx2+8mP7W8APBABAr402aIgyGry7cprdOt38vd
lFaL5KnWhcl+9s+Xz7/rrcvg36Jfu5fIahK7jPHKHZqxP80yLY9h6WmtPV/u6yGqMsM+XC
H1ZBdvgUOBxIGdv9DCQBXu2LbS4kej78fQWKwvKb6/VwpG/vuvx9CT6J689RTiCUMbCSER
vvZN4hEzyJ2itB+cu2cxW4KD+/t2mBXW5qUJoEbe/AhkSCL/gGsEs5Oavn9LEeZLeOVRCD
ISd/F37O0tG+vVtKetAAABADVtP4eRO0IcMtO9ZbxYtvoIorcqCH2XQGN5iEitpyrgOohJ
uvzzMt/7ZdTBSlI6Ki624w1uA2NbcTGP4bDKvOYDFUP7u2z/VLFToI+aElwNcNQBogQsoa
tPRqG997vx+j+MsHlEMxM96MCej7TKLAbfSlqYk+WC4h41SkqiuAPEzTaIQEbIGAAG9aKe
bvxLbR3wRoKSlONeezms39W9RSzOFObeirlEi8qZ8KS0XlrbRsIpq9VhSRgZZiMZgBLkjK
d8AraKYinAqwrToPG7ck15Bgs0PA0gJzrRhqLUmWV6neuBn+QWV5j1huGQ2L2EbIc0dgJs
bCCLlxDIGCYDkJ8AAAEBAPohkD6lgEKsWLdv2ZUOLjnegu2g8tvG4dYf0sn9Pz7iGGm/AP
us4hy/ymt+aIYF8RO8UThoUnJTI1kBtEvpnHAmBU2A9ki4x7ftImdRTZyGjyLMyjLg/ncj
JNqAGJ26YYd6uFqrtk6JCAfbNGmhycgggF+kjENMP0eie2aqwRRYEbA8KZ0xj8u1697m3N
SEHxXX23r7ZWpdk9iMOnj7okmGJwa3YcCmTvu/uHb4UQZf9meQ2CWLV39SICfGEnkbRoWO
oYoo8wWgmNdGgwOv4gouB0rymF7ev4MhqN1mwObN02TblWScbQBHZbt9RCaZi88R0e1feH
thFU0J4E4nt8MAAAEBALjl6RMApt4lgM+OPiDnc4G+ipcn5AAxpffu7eK08axcQ2JB2k8I
wp086eGzjuqjwcqnlYCX1hUVdzVEOv5/m75UiYuqvKsB6hkB54ZQv+neevgOeAo8YQC+/I
PdJA6o+oTPe9v/zi9ORozn4B4CUcjqtUHNQG14RvCMY+HP5Xc9SzoW4c5NoyvhJ+qgi/zy
uKk/0IXnbr3BgM6EzQac8/FvhZ08vh966zPZXlXKv3Z9J+Pk3xkL9X75GzqiwN4ZJDPnUl
nMP2QOwgA9g1CJRJq0664OsrzGZGwIPyHhdsI2OURdGhjcGX/MVnWdHCVoH+ucAlum+u7Q
Ehkch47TeBMAAAAYc2FteW1hdGVydTE5OTlAZ21haWwuY29tAQID
-----END OPENSSH PRIVATE KEY-----
"
          script: |
            cd /home/ubuntu/my-fastapi-app  # Change to your FastAPI project path
            git pull origin main            # Pull latest changes
            source venv/bin/activate        # Activate virtual environment
            pip install -r requirements.txt  # Install dependencies
            sudo systemctl restart fastapi   # Restart FastAPI service
